import { AdminOverrides } from '../types';

// This file was generated by the admin panel.
// To publish your changes, copy this entire file's content
// and replace the content of 'overrides/data.ts'.

export const staticOverrides: AdminOverrides = {
  "anime": {
    "97668": {
      "streamUrlTemplates": {
        "vidnest": "https://vidnest.fun/anime/108945"
      }
    }
  },
  "globalStreamUrlTemplates": {}
};